//! The main tests module

#![warn(clippy::pedantic)]
#![allow(clippy::bool_assert_comparison)]
#![allow(clippy::enum_glob_use)]
#![allow(clippy::module_name_repetitions)]
#![allow(clippy::return_self_not_must_use)]
#![allow(clippy::similar_names)]
#![warn(clippy::allow_attributes)]
#![warn(clippy::arbitrary_source_item_ordering)]
#![warn(clippy::assertions_on_result_states)]
#![warn(clippy::branches_sharing_code)]
#![warn(clippy::collection_is_never_read)]
#![warn(clippy::create_dir)]
#![warn(clippy::dbg_macro)]
#![warn(clippy::derive_partial_eq_without_eq)]
#![warn(clippy::doc_link_code)]
#![warn(clippy::else_if_without_else)]
#![warn(clippy::empty_enum_variants_with_brackets)]
#![warn(clippy::empty_structs_with_brackets)]
#![warn(clippy::equatable_if_let)]
#![warn(clippy::fallible_impl_from)]
#![warn(clippy::fn_to_numeric_cast_any)]
#![warn(clippy::get_unwrap)]
#![warn(clippy::if_then_some_else_none)]
#![warn(clippy::impl_trait_in_params)]
#![warn(clippy::implicit_clone)]
#![warn(clippy::infinite_loop)]
#![warn(clippy::iter_on_empty_collections)]
#![warn(clippy::iter_on_single_items)]
#![warn(clippy::iter_with_drain)]
#![warn(clippy::iter_without_into_iter)]
#![warn(clippy::large_stack_frames)]
#![warn(clippy::literal_string_with_formatting_args)]
#![warn(clippy::lossy_float_literal)]
#![warn(clippy::map_with_unused_argument_over_ranges)]
#![warn(clippy::missing_const_for_fn)]
#![warn(clippy::mixed_read_write_in_expression)]
#![warn(clippy::multiple_inherent_impl)]
#![warn(clippy::needless_collect)]
#![warn(clippy::needless_pass_by_ref_mut)]
#![warn(clippy::needless_raw_strings)]
#![warn(clippy::non_zero_suggestions)]
#![warn(clippy::nonstandard_macro_braces)]
#![warn(clippy::or_fun_call)]
#![warn(clippy::partial_pub_fields)]
#![warn(clippy::path_buf_push_overwrite)]
#![warn(clippy::pathbuf_init_then_push)]
#![warn(clippy::precedence_bits)]
#![warn(clippy::pub_without_shorthand)]
#![warn(clippy::rc_mutex)]
#![warn(clippy::redundant_clone)]
#![warn(clippy::redundant_pub_crate)]
#![warn(clippy::redundant_type_annotations)]
#![warn(clippy::ref_patterns)]
#![warn(clippy::renamed_function_params)]
#![warn(clippy::rest_pat_in_fully_bound_structs)]
#![warn(clippy::same_name_method)]
#![warn(clippy::semicolon_inside_block)]
#![warn(clippy::single_option_map)]
#![warn(clippy::std_instead_of_core)]
#![warn(clippy::str_to_string)]
#![warn(clippy::string_lit_chars_any)]
#![warn(clippy::suboptimal_flops)]
#![warn(clippy::suspicious_operation_groupings)]
#![warn(clippy::suspicious_xor_used_as_pow)]
#![warn(clippy::todo)]
#![warn(clippy::too_long_first_doc_paragraph)]
#![warn(clippy::trait_duplication_in_bounds)]
#![warn(clippy::try_err)]
#![warn(clippy::tuple_array_conversions)]
#![warn(clippy::type_repetition_in_bounds)]
#![warn(clippy::undocumented_unsafe_blocks)]
#![warn(clippy::unimplemented)]
#![warn(clippy::unnecessary_safety_comment)]
#![warn(clippy::unnecessary_safety_doc)]
#![warn(clippy::unnecessary_self_imports)]
#![warn(clippy::unnecessary_struct_initialization)]
#![warn(clippy::unneeded_field_pattern)]
#![warn(clippy::unused_peekable)]
#![warn(clippy::unused_result_ok)]
#![warn(clippy::unused_rounding)]
#![warn(clippy::use_self)]
#![warn(clippy::useless_let_if_seq)]
#![warn(clippy::verbose_file_reads)]

#[cfg(feature = "std")]
mod dowild_with;
#[cfg(feature = "std")]
mod import;
#[cfg(feature = "std")]
mod options;
